apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: jhon-silva-38
  labels:
    app: unified-frontend
    component: service
spec:
  type: LoadBalancer
  selector:
    app: unified-frontend
    name: frontend-deployment
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
